<?php

// Generated by ContainerShapeTest with INDEXNOWKIT_UPDATE_SHAPE=1; do not edit.

return array (
  'sync with doctrine, profiler and sitemap' => 
  array (
    'definitions' => 
    array (
      'indexnowkit.config' => 
      array (
        'class' => 'IndexNowKit\\Config',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.key_provider' => 
      array (
        'class' => 'IndexNowKit\\Key\\StaticKeyProvider',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.transport.real' => 
      array (
        'class' => 'IndexNowKit\\Http\\TransportInterface',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.transport' => 
      array (
        'class' => 'IndexNowKit\\Http\\LazyTransport',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.url_normalizer' => 
      array (
        'class' => 'IndexNowKit\\Url\\UrlNormalizer',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.throttle' => 
      array (
        'class' => 'IndexNowKit\\Throttle\\TokenBucket',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.client' => 
      array (
        'class' => 'IndexNowKit\\Client',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.debounce_store.psr16' => 
      array (
        'class' => 'Symfony\\Component\\Cache\\Psr16Cache',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.debounce_store' => 
      array (
        'class' => 'IndexNowKit\\Debounce\\Psr16DebounceStore',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.submission_store' => 
      array (
        'class' => 'IndexNowKit\\Submission\\NullSubmissionStore',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.submitter' => 
      array (
        'class' => 'IndexNowKit\\Submitter',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.collector' => 
      array (
        'class' => 'IndexNowKit\\Collector\\Collector',
        'tags' => 
        array (
          'kernel.reset' => 
          array (
            0 => 
            array (
              'method' => 'reset',
            ),
          ),
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.attribute_reader' => 
      array (
        'class' => 'IndexNowKit\\Attribute\\AttributeReader',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.route_url_resolver' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Url\\SymfonyRouteUrlResolver',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.resolver_locator' => 
      array (
        'class' => 'IndexNowKit\\Url\\ArrayResolverLocator',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.url_resolver' => 
      array (
        'class' => 'IndexNowKit\\Url\\AttributeUrlResolver',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.guarded_url_resolver' => 
      array (
        'class' => 'IndexNowKit\\Url\\GuardedUrlResolver',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.change_handler' => 
      array (
        'class' => 'IndexNowKit\\Url\\ObjectChangeHandler',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.dispatcher' => 
      array (
        'class' => 'IndexNowKit\\Dispatch\\SyncDispatcher',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit' => 
      array (
        'class' => 'IndexNowKit\\IndexNowKit',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.flush_listener' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\EventListener\\FlushListener',
        'tags' => 
        array (
          'kernel.event_listener' => 
          array (
            0 => 
            array (
              'event' => 'kernel.terminate',
              'method' => 'onTerminate',
              'priority' => -1000,
            ),
            1 => 
            array (
              'event' => 'console.terminate',
              'method' => 'onTerminate',
              'priority' => -1024,
            ),
            2 => 
            array (
              'event' => 'Symfony\\Component\\Messenger\\Event\\WorkerMessageHandledEvent',
              'method' => 'onTerminate',
              'priority' => -1024,
            ),
          ),
        ),
      ),
      'indexnowkit.key_file_responder' => 
      array (
        'class' => 'IndexNowKit\\Key\\KeyFileResponder',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.key_file_routes' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Routing\\KeyFileRouteLoader',
        'tags' => 
        array (
          'routing.route_loader' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Controller\\KeyFileController' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'controller.service_arguments' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.result_recorder' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\DataCollector\\ResultRecorder',
        'tags' => 
        array (
          'kernel.reset' => 
          array (
            0 => 
            array (
              'method' => 'reset',
            ),
          ),
        ),
      ),
      'indexnowkit.data_collector' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\DataCollector\\IndexNowDataCollector',
        'tags' => 
        array (
          'data_collector' => 
          array (
            0 => 
            array (
              'template' => '@IndexNowKit/data_collector/indexnow.html.twig',
              'id' => 'indexnow',
              'priority' => 250,
            ),
          ),
        ),
      ),
      'indexnowkit.check.wiring' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Check\\WiringCheck',
        'tags' => 
        array (
          'indexnowkit.check' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.check.debounce_store.probe' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Check\\CacheProbe',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.check.debounce_store.probe_closure' => 
      array (
        'class' => 'Closure',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.check.debounce_store' => 
      array (
        'class' => 'IndexNowKit\\Check\\DebounceStoreCheck',
        'tags' => 
        array (
          'indexnowkit.check' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.checker' => 
      array (
        'class' => 'IndexNowKit\\Check\\Checker',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.console.vocabulary' => 
      array (
        'class' => 'IndexNowKit\\Console\\Vocabulary',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.result_formatter' => 
      array (
        'class' => 'IndexNowKit\\Console\\ResultRenderer',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.command_submitter_factory' => 
      array (
        'class' => 'IndexNowKit\\Adapter\\SubmitterFactory',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.sitemap_config' => 
      array (
        'class' => 'IndexNowKit\\Sitemap\\SitemapConfig',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.check.sitemap_spool' => 
      array (
        'class' => 'IndexNowKit\\Sitemap\\Check\\SitemapSpoolCheck',
        'tags' => 
        array (
          'indexnowkit.check' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.sitemap_reader' => 
      array (
        'class' => 'IndexNowKit\\Sitemap\\SitemapReader',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.console.sitemap' => 
      array (
        'class' => 'IndexNowKit\\Sitemap\\Console\\SitemapRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\SitemapCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.key_generate' => 
      array (
        'class' => 'IndexNowKit\\Console\\KeyGenerateRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\KeyGenerateCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.check' => 
      array (
        'class' => 'IndexNowKit\\Console\\CheckRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\CheckCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.submit' => 
      array (
        'class' => 'IndexNowKit\\Console\\SubmitRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\SubmitCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.entity_loader' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Command\\EntityLoader',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.console.submit_entity' => 
      array (
        'class' => 'IndexNowKit\\Console\\SubmitSubjectsRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\SubmitEntityCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.explain' => 
      array (
        'class' => 'IndexNowKit\\Console\\ExplainRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\ExplainCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.doctrine.staging' => 
      array (
        'class' => 'IndexNowKit\\Transaction\\TransactionStaging',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.doctrine.sink' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Doctrine\\StagingSink',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.doctrine.middleware' => 
      array (
        'class' => 'IndexNowKit\\Doctrine\\Middleware\\IndexNowMiddleware',
        'tags' => 
        array (
          'doctrine.middleware' => 
          array (
            0 => 
            array (
              'connection' => 'default',
            ),
            1 => 
            array (
              'connection' => 'archive',
            ),
          ),
        ),
      ),
      'indexnowkit.doctrine.listener' => 
      array (
        'class' => 'IndexNowKit\\Doctrine\\IndexNowListener',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
          'doctrine.event_listener' => 
          array (
            0 => 
            array (
              'event' => 'onFlush',
              'priority' => -100,
              'connection' => 'default',
            ),
            1 => 
            array (
              'event' => 'postFlush',
              'priority' => -100,
              'connection' => 'default',
            ),
            2 => 
            array (
              'event' => 'onFlush',
              'priority' => -100,
              'connection' => 'archive',
            ),
            3 => 
            array (
              'event' => 'postFlush',
              'priority' => -100,
              'connection' => 'archive',
            ),
          ),
        ),
      ),
    ),
    'aliases' => 
    array (
      'IndexNowKit\\Config' => 'indexnowkit.config',
      'IndexNowKit\\Key\\KeyProviderInterface' => 'indexnowkit.key_provider',
      'IndexNowKit\\Http\\TransportInterface' => 'indexnowkit.transport',
      'IndexNowKit\\Url\\UrlNormalizerInterface' => 'indexnowkit.url_normalizer',
      'IndexNowKit\\Throttle\\ThrottleInterface' => 'indexnowkit.throttle',
      'IndexNowKit\\ClientInterface' => 'indexnowkit.client',
      'IndexNowKit\\Debounce\\DebounceStoreInterface' => 'indexnowkit.debounce_store',
      'IndexNowKit\\Submission\\SubmissionStoreInterface' => 'indexnowkit.submission_store',
      'IndexNowKit\\Submitter' => 'indexnowkit.submitter',
      'IndexNowKit\\SubmitterInterface' => 'indexnowkit.submitter',
      'IndexNowKit\\Collector\\Collector' => 'indexnowkit.collector',
      'IndexNowKit\\Collector\\CollectorInterface' => 'indexnowkit.collector',
      'IndexNowKit\\Attribute\\AttributeReader' => 'indexnowkit.attribute_reader',
      'IndexNowKit\\Attribute\\AttributeReaderInterface' => 'indexnowkit.attribute_reader',
      'IndexNowKit\\Url\\RouteUrlResolverInterface' => 'indexnowkit.route_url_resolver',
      'IndexNowKit\\Url\\ResolverLocatorInterface' => 'indexnowkit.resolver_locator',
      'IndexNowKit\\Url\\UrlResolverInterface' => 'indexnowkit.url_resolver',
      'IndexNowKit\\Url\\GuardedUrlResolver' => 'indexnowkit.guarded_url_resolver',
      'IndexNowKit\\Url\\ObjectChangeHandler' => 'indexnowkit.change_handler',
      'IndexNowKit\\Dispatch\\DispatcherInterface' => 'indexnowkit.dispatcher',
      'IndexNowKit\\IndexNowKit' => 'indexnowkit',
      'IndexNowKit\\Key\\KeyFileResponder' => 'indexnowkit.key_file_responder',
      'IndexNowKit\\Check\\CheckerInterface' => 'indexnowkit.checker',
      'IndexNowKit\\Console\\ResultFormatterInterface' => 'indexnowkit.result_formatter',
      'IndexNowKit\\Adapter\\SubmitterFactoryInterface' => 'indexnowkit.command_submitter_factory',
      'IndexNowKit\\Sitemap\\SitemapConfig' => 'indexnowkit.sitemap_config',
      'IndexNowKit\\Sitemap\\SitemapReader' => 'indexnowkit.sitemap_reader',
      'IndexNowKit\\Sitemap\\SitemapSourceInterface' => 'indexnowkit.sitemap_reader',
      'IndexNowKit\\Console\\SubjectLoaderInterface' => 'indexnowkit.entity_loader',
    ),
  ),
  'messenger without doctrine, psr16 store, sitemap not installed' => 
  array (
    'definitions' => 
    array (
      'indexnowkit.config' => 
      array (
        'class' => 'IndexNowKit\\Config',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.key_provider' => 
      array (
        'class' => 'IndexNowKit\\Key\\StaticKeyProvider',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.transport.real' => 
      array (
        'class' => 'IndexNowKit\\Http\\TransportInterface',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.transport' => 
      array (
        'class' => 'IndexNowKit\\Http\\LazyTransport',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.url_normalizer' => 
      array (
        'class' => 'IndexNowKit\\Url\\UrlNormalizer',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.throttle' => 
      array (
        'class' => 'IndexNowKit\\Throttle\\TokenBucket',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.client' => 
      array (
        'class' => 'IndexNowKit\\Client',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.debounce_store.psr16' => 
      array (
        'class' => 'Symfony\\Component\\Cache\\Psr16Cache',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.debounce_store' => 
      array (
        'class' => 'IndexNowKit\\Debounce\\Psr16DebounceStore',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.submission_store' => 
      array (
        'class' => 'IndexNowKit\\Submission\\NullSubmissionStore',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.submitter' => 
      array (
        'class' => 'IndexNowKit\\Submitter',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.collector' => 
      array (
        'class' => 'IndexNowKit\\Collector\\Collector',
        'tags' => 
        array (
          'kernel.reset' => 
          array (
            0 => 
            array (
              'method' => 'reset',
            ),
          ),
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.attribute_reader' => 
      array (
        'class' => 'IndexNowKit\\Attribute\\AttributeReader',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.route_url_resolver' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Url\\SymfonyRouteUrlResolver',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.resolver_locator' => 
      array (
        'class' => 'IndexNowKit\\Url\\ArrayResolverLocator',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.url_resolver' => 
      array (
        'class' => 'IndexNowKit\\Url\\AttributeUrlResolver',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.guarded_url_resolver' => 
      array (
        'class' => 'IndexNowKit\\Url\\GuardedUrlResolver',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.change_handler' => 
      array (
        'class' => 'IndexNowKit\\Url\\ObjectChangeHandler',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.dispatcher' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Messenger\\MessengerDispatcher',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.messenger.handler' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Messenger\\SubmitUrlsHandler',
        'tags' => 
        array (
          'messenger.message_handler' => 
          array (
            0 => 
            array (
            ),
          ),
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit' => 
      array (
        'class' => 'IndexNowKit\\IndexNowKit',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.flush_listener' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\EventListener\\FlushListener',
        'tags' => 
        array (
          'kernel.event_listener' => 
          array (
            0 => 
            array (
              'event' => 'kernel.terminate',
              'method' => 'onTerminate',
              'priority' => -1000,
            ),
            1 => 
            array (
              'event' => 'console.terminate',
              'method' => 'onTerminate',
              'priority' => -1024,
            ),
            2 => 
            array (
              'event' => 'Symfony\\Component\\Messenger\\Event\\WorkerMessageHandledEvent',
              'method' => 'onTerminate',
              'priority' => -1024,
            ),
          ),
        ),
      ),
      'indexnowkit.key_file_responder' => 
      array (
        'class' => 'IndexNowKit\\Key\\KeyFileResponder',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.key_file_routes' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Routing\\KeyFileRouteLoader',
        'tags' => 
        array (
          'routing.route_loader' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Controller\\KeyFileController' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'controller.service_arguments' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.check.wiring' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Check\\WiringCheck',
        'tags' => 
        array (
          'indexnowkit.check' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.check.debounce_store.probe' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Check\\CacheProbe',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.check.debounce_store.probe_closure' => 
      array (
        'class' => 'Closure',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.check.debounce_store' => 
      array (
        'class' => 'IndexNowKit\\Check\\DebounceStoreCheck',
        'tags' => 
        array (
          'indexnowkit.check' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.checker' => 
      array (
        'class' => 'IndexNowKit\\Check\\Checker',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.console.vocabulary' => 
      array (
        'class' => 'IndexNowKit\\Console\\Vocabulary',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.result_formatter' => 
      array (
        'class' => 'IndexNowKit\\Console\\ResultRenderer',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.command_submitter_factory' => 
      array (
        'class' => 'IndexNowKit\\Adapter\\SubmitterFactory',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.check.sitemap_missing' => 
      array (
        'class' => 'IndexNowKit\\Check\\StaticCheck',
        'tags' => 
        array (
          'indexnowkit.check' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\SitemapNotInstalledCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.key_generate' => 
      array (
        'class' => 'IndexNowKit\\Console\\KeyGenerateRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\KeyGenerateCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.check' => 
      array (
        'class' => 'IndexNowKit\\Console\\CheckRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\CheckCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.submit' => 
      array (
        'class' => 'IndexNowKit\\Console\\SubmitRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\SubmitCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
    ),
    'aliases' => 
    array (
      'IndexNowKit\\Config' => 'indexnowkit.config',
      'IndexNowKit\\Key\\KeyProviderInterface' => 'indexnowkit.key_provider',
      'IndexNowKit\\Http\\TransportInterface' => 'indexnowkit.transport',
      'IndexNowKit\\Url\\UrlNormalizerInterface' => 'indexnowkit.url_normalizer',
      'IndexNowKit\\Throttle\\ThrottleInterface' => 'indexnowkit.throttle',
      'IndexNowKit\\ClientInterface' => 'indexnowkit.client',
      'IndexNowKit\\Debounce\\DebounceStoreInterface' => 'indexnowkit.debounce_store',
      'IndexNowKit\\Submission\\SubmissionStoreInterface' => 'indexnowkit.submission_store',
      'IndexNowKit\\Submitter' => 'indexnowkit.submitter',
      'IndexNowKit\\SubmitterInterface' => 'indexnowkit.submitter',
      'IndexNowKit\\Collector\\Collector' => 'indexnowkit.collector',
      'IndexNowKit\\Collector\\CollectorInterface' => 'indexnowkit.collector',
      'IndexNowKit\\Attribute\\AttributeReader' => 'indexnowkit.attribute_reader',
      'IndexNowKit\\Attribute\\AttributeReaderInterface' => 'indexnowkit.attribute_reader',
      'IndexNowKit\\Url\\RouteUrlResolverInterface' => 'indexnowkit.route_url_resolver',
      'IndexNowKit\\Url\\ResolverLocatorInterface' => 'indexnowkit.resolver_locator',
      'IndexNowKit\\Url\\UrlResolverInterface' => 'indexnowkit.url_resolver',
      'IndexNowKit\\Url\\GuardedUrlResolver' => 'indexnowkit.guarded_url_resolver',
      'IndexNowKit\\Url\\ObjectChangeHandler' => 'indexnowkit.change_handler',
      'IndexNowKit\\Dispatch\\DispatcherInterface' => 'indexnowkit.dispatcher',
      'IndexNowKit\\IndexNowKit' => 'indexnowkit',
      'IndexNowKit\\Key\\KeyFileResponder' => 'indexnowkit.key_file_responder',
      'IndexNowKit\\Check\\CheckerInterface' => 'indexnowkit.checker',
      'IndexNowKit\\Console\\ResultFormatterInterface' => 'indexnowkit.result_formatter',
      'IndexNowKit\\Adapter\\SubmitterFactoryInterface' => 'indexnowkit.command_submitter_factory',
    ),
  ),
  'disabled' => 
  array (
    'definitions' => 
    array (
      'indexnowkit.config' => 
      array (
        'class' => 'IndexNowKit\\Config',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.key_provider' => 
      array (
        'class' => 'IndexNowKit\\Key\\StaticKeyProvider',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.transport.real' => 
      array (
        'class' => 'IndexNowKit\\Http\\TransportInterface',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.transport' => 
      array (
        'class' => 'IndexNowKit\\Http\\LazyTransport',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.url_normalizer' => 
      array (
        'class' => 'IndexNowKit\\Url\\UrlNormalizer',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.throttle' => 
      array (
        'class' => 'IndexNowKit\\Throttle\\TokenBucket',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.client' => 
      array (
        'class' => 'IndexNowKit\\Client',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.debounce_store' => 
      array (
        'class' => 'IndexNowKit\\Debounce\\NullDebounceStore',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.submission_store' => 
      array (
        'class' => 'IndexNowKit\\Submission\\NullSubmissionStore',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.submitter' => 
      array (
        'class' => 'IndexNowKit\\Submitter',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.collector' => 
      array (
        'class' => 'IndexNowKit\\Collector\\Collector',
        'tags' => 
        array (
          'kernel.reset' => 
          array (
            0 => 
            array (
              'method' => 'reset',
            ),
          ),
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.attribute_reader' => 
      array (
        'class' => 'IndexNowKit\\Attribute\\AttributeReader',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.route_url_resolver' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Url\\SymfonyRouteUrlResolver',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.resolver_locator' => 
      array (
        'class' => 'IndexNowKit\\Url\\ArrayResolverLocator',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.url_resolver' => 
      array (
        'class' => 'IndexNowKit\\Url\\AttributeUrlResolver',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.guarded_url_resolver' => 
      array (
        'class' => 'IndexNowKit\\Url\\GuardedUrlResolver',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.change_handler' => 
      array (
        'class' => 'IndexNowKit\\Url\\ObjectChangeHandler',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.dispatcher' => 
      array (
        'class' => 'IndexNowKit\\Dispatch\\NullDispatcher',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit' => 
      array (
        'class' => 'IndexNowKit\\IndexNowKit',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.flush_listener' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\EventListener\\FlushListener',
        'tags' => 
        array (
          'kernel.event_listener' => 
          array (
            0 => 
            array (
              'event' => 'kernel.terminate',
              'method' => 'onTerminate',
              'priority' => -1000,
            ),
            1 => 
            array (
              'event' => 'console.terminate',
              'method' => 'onTerminate',
              'priority' => -1024,
            ),
            2 => 
            array (
              'event' => 'Symfony\\Component\\Messenger\\Event\\WorkerMessageHandledEvent',
              'method' => 'onTerminate',
              'priority' => -1024,
            ),
          ),
        ),
      ),
      'indexnowkit.key_file_responder' => 
      array (
        'class' => 'IndexNowKit\\Key\\KeyFileResponder',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.key_file_routes' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Routing\\KeyFileRouteLoader',
        'tags' => 
        array (
          'routing.route_loader' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Controller\\KeyFileController' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'controller.service_arguments' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.check.wiring' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Check\\WiringCheck',
        'tags' => 
        array (
          'indexnowkit.check' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.check.debounce_store' => 
      array (
        'class' => 'IndexNowKit\\Check\\DebounceStoreCheck',
        'tags' => 
        array (
          'indexnowkit.check' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.checker' => 
      array (
        'class' => 'IndexNowKit\\Check\\Checker',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.console.vocabulary' => 
      array (
        'class' => 'IndexNowKit\\Console\\Vocabulary',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.result_formatter' => 
      array (
        'class' => 'IndexNowKit\\Console\\ResultRenderer',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.command_submitter_factory' => 
      array (
        'class' => 'IndexNowKit\\Adapter\\SubmitterFactory',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.sitemap_config' => 
      array (
        'class' => 'IndexNowKit\\Sitemap\\SitemapConfig',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.check.sitemap_spool' => 
      array (
        'class' => 'IndexNowKit\\Sitemap\\Check\\SitemapSpoolCheck',
        'tags' => 
        array (
          'indexnowkit.check' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.sitemap_reader' => 
      array (
        'class' => 'IndexNowKit\\Sitemap\\SitemapReader',
        'tags' => 
        array (
          'monolog.logger' => 
          array (
            0 => 
            array (
              'channel' => 'indexnow',
            ),
          ),
        ),
      ),
      'indexnowkit.console.sitemap' => 
      array (
        'class' => 'IndexNowKit\\Sitemap\\Console\\SitemapRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\SitemapCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.key_generate' => 
      array (
        'class' => 'IndexNowKit\\Console\\KeyGenerateRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\KeyGenerateCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.check' => 
      array (
        'class' => 'IndexNowKit\\Console\\CheckRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\CheckCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.submit' => 
      array (
        'class' => 'IndexNowKit\\Console\\SubmitRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\SubmitCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.entity_loader' => 
      array (
        'class' => 'IndexNowKit\\SymfonyBundle\\Command\\EntityLoader',
        'tags' => 
        array (
        ),
      ),
      'indexnowkit.console.submit_entity' => 
      array (
        'class' => 'IndexNowKit\\Console\\SubmitSubjectsRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\SubmitEntityCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
      'indexnowkit.console.explain' => 
      array (
        'class' => 'IndexNowKit\\Console\\ExplainRunner',
        'tags' => 
        array (
        ),
      ),
      'IndexNowKit\\SymfonyBundle\\Command\\ExplainCommand' => 
      array (
        'class' => NULL,
        'tags' => 
        array (
          'console.command' => 
          array (
            0 => 
            array (
            ),
          ),
        ),
      ),
    ),
    'aliases' => 
    array (
      'IndexNowKit\\Config' => 'indexnowkit.config',
      'IndexNowKit\\Key\\KeyProviderInterface' => 'indexnowkit.key_provider',
      'IndexNowKit\\Http\\TransportInterface' => 'indexnowkit.transport',
      'IndexNowKit\\Url\\UrlNormalizerInterface' => 'indexnowkit.url_normalizer',
      'IndexNowKit\\Throttle\\ThrottleInterface' => 'indexnowkit.throttle',
      'IndexNowKit\\ClientInterface' => 'indexnowkit.client',
      'IndexNowKit\\Debounce\\DebounceStoreInterface' => 'indexnowkit.debounce_store',
      'IndexNowKit\\Submission\\SubmissionStoreInterface' => 'indexnowkit.submission_store',
      'IndexNowKit\\Submitter' => 'indexnowkit.submitter',
      'IndexNowKit\\SubmitterInterface' => 'indexnowkit.submitter',
      'IndexNowKit\\Collector\\Collector' => 'indexnowkit.collector',
      'IndexNowKit\\Collector\\CollectorInterface' => 'indexnowkit.collector',
      'IndexNowKit\\Attribute\\AttributeReader' => 'indexnowkit.attribute_reader',
      'IndexNowKit\\Attribute\\AttributeReaderInterface' => 'indexnowkit.attribute_reader',
      'IndexNowKit\\Url\\RouteUrlResolverInterface' => 'indexnowkit.route_url_resolver',
      'IndexNowKit\\Url\\ResolverLocatorInterface' => 'indexnowkit.resolver_locator',
      'IndexNowKit\\Url\\UrlResolverInterface' => 'indexnowkit.url_resolver',
      'IndexNowKit\\Url\\GuardedUrlResolver' => 'indexnowkit.guarded_url_resolver',
      'IndexNowKit\\Url\\ObjectChangeHandler' => 'indexnowkit.change_handler',
      'IndexNowKit\\Dispatch\\DispatcherInterface' => 'indexnowkit.dispatcher',
      'IndexNowKit\\IndexNowKit' => 'indexnowkit',
      'IndexNowKit\\Key\\KeyFileResponder' => 'indexnowkit.key_file_responder',
      'IndexNowKit\\Check\\CheckerInterface' => 'indexnowkit.checker',
      'IndexNowKit\\Console\\ResultFormatterInterface' => 'indexnowkit.result_formatter',
      'IndexNowKit\\Adapter\\SubmitterFactoryInterface' => 'indexnowkit.command_submitter_factory',
      'IndexNowKit\\Sitemap\\SitemapConfig' => 'indexnowkit.sitemap_config',
      'IndexNowKit\\Sitemap\\SitemapReader' => 'indexnowkit.sitemap_reader',
      'IndexNowKit\\Sitemap\\SitemapSourceInterface' => 'indexnowkit.sitemap_reader',
      'IndexNowKit\\Console\\SubjectLoaderInterface' => 'indexnowkit.entity_loader',
    ),
  ),
);
